/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tpoo.interfaces;

import java.awt.Dimension;

/**
 *
 * @author Maestro 302
 */
public class MdiApplication extends javax.swing.JFrame {

    /**
     * Creates new form MdiApplication
     */
    public MdiApplication() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuArchivoExportar = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuArchivoSalir = new javax.swing.JMenuItem();
        menuMantenedores = new javax.swing.JMenu();
        menuMantenedoresAlumnos = new javax.swing.JMenuItem();
        menuMantenedoresDocentes = new javax.swing.JMenuItem();
        menuMantenedoresAdministrativos = new javax.swing.JMenuItem();
        menuMantenedoresAuxiliares = new javax.swing.JMenuItem();
        menuInformes = new javax.swing.JMenu();
        menuInformeNotas = new javax.swing.JMenuItem();
        menuInformeAsistencia = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuInformeMatricula = new javax.swing.JMenuItem();
        menuInformeMensualidad = new javax.swing.JMenuItem();
        menuInformes1 = new javax.swing.JMenu();
        menuInformeNotas1 = new javax.swing.JMenuItem();
        menuInformeAsistencia1 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menuInformeMatricula1 = new javax.swing.JMenuItem();
        menuInformeMensualidad1 = new javax.swing.JMenuItem();
        menuProcesos = new javax.swing.JMenu();
        menuProcesosNotas = new javax.swing.JMenuItem();
        menuProcesosAsistencia = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        menuProcesosMatricula = new javax.swing.JMenuItem();
        menuProcesosMensualidad = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        menuAyudaContenidos = new javax.swing.JMenuItem();
        menuAyudaAcercaDe = new javax.swing.JMenuItem();
        menuAyuda1 = new javax.swing.JMenu();
        menuAyudaContenidos1 = new javax.swing.JMenuItem();
        menuAyudaAcercaDe1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuArchivo.setMnemonic('f');
        menuArchivo.setText("Archivo");

        menuArchivoExportar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuArchivoExportar.setMnemonic('o');
        menuArchivoExportar.setText("Opciones");
        menuArchivoExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArchivoExportarActionPerformed(evt);
            }
        });
        menuArchivo.add(menuArchivoExportar);

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem11.setText("Exportar");
        menuArchivo.add(jMenuItem11);
        menuArchivo.add(jSeparator1);

        menuArchivoSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        menuArchivoSalir.setMnemonic('x');
        menuArchivoSalir.setText("Salir");
        menuArchivoSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArchivoSalirActionPerformed(evt);
            }
        });
        menuArchivo.add(menuArchivoSalir);

        menuBar.add(menuArchivo);

        menuMantenedores.setMnemonic('e');
        menuMantenedores.setText("Mantenedores");

        menuMantenedoresAlumnos.setMnemonic('t');
        menuMantenedoresAlumnos.setText("Alumnos");
        menuMantenedores.add(menuMantenedoresAlumnos);

        menuMantenedoresDocentes.setMnemonic('y');
        menuMantenedoresDocentes.setText("Docentes");
        menuMantenedoresDocentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMantenedoresDocentesActionPerformed(evt);
            }
        });
        menuMantenedores.add(menuMantenedoresDocentes);

        menuMantenedoresAdministrativos.setMnemonic('p');
        menuMantenedoresAdministrativos.setText("Administrativos");
        menuMantenedores.add(menuMantenedoresAdministrativos);

        menuMantenedoresAuxiliares.setMnemonic('d');
        menuMantenedoresAuxiliares.setText("Auxiliares");
        menuMantenedores.add(menuMantenedoresAuxiliares);

        menuInformes.setText("Informes");

        menuInformeNotas.setText("Notas");
        menuInformeNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInformeNotasActionPerformed(evt);
            }
        });
        menuInformes.add(menuInformeNotas);

        menuInformeAsistencia.setText("Asistencia");
        menuInformes.add(menuInformeAsistencia);
        menuInformes.add(jSeparator3);

        menuInformeMatricula.setText("Matrícula");
        menuInformes.add(menuInformeMatricula);

        menuInformeMensualidad.setText("Mensualidad");
        menuInformes.add(menuInformeMensualidad);

        menuMantenedores.add(menuInformes);

        menuBar.add(menuMantenedores);

        menuInformes1.setText("Informes");

        menuInformeNotas1.setText("Notas");
        menuInformeNotas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInformeNotas1ActionPerformed(evt);
            }
        });
        menuInformes1.add(menuInformeNotas1);

        menuInformeAsistencia1.setText("Asistencia");
        menuInformes1.add(menuInformeAsistencia1);
        menuInformes1.add(jSeparator4);

        menuInformeMatricula1.setText("Matrícula");
        menuInformes1.add(menuInformeMatricula1);

        menuInformeMensualidad1.setText("Mensualidad");
        menuInformes1.add(menuInformeMensualidad1);

        menuBar.add(menuInformes1);

        menuProcesos.setText("Procesos");

        menuProcesosNotas.setText("Notas");
        menuProcesosNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProcesosNotasActionPerformed(evt);
            }
        });
        menuProcesos.add(menuProcesosNotas);

        menuProcesosAsistencia.setText("Asistencia");
        menuProcesos.add(menuProcesosAsistencia);
        menuProcesos.add(jSeparator5);

        menuProcesosMatricula.setText("Matrícula");
        menuProcesos.add(menuProcesosMatricula);

        menuProcesosMensualidad.setText("Mensualidad");
        menuProcesos.add(menuProcesosMensualidad);

        menuAyuda.setMnemonic('h');
        menuAyuda.setText("Ayuda");

        menuAyudaContenidos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        menuAyudaContenidos.setMnemonic('c');
        menuAyudaContenidos.setText("Contenidos");
        menuAyuda.add(menuAyudaContenidos);

        menuAyudaAcercaDe.setMnemonic('a');
        menuAyudaAcercaDe.setText("Acerca de...");
        menuAyuda.add(menuAyudaAcercaDe);

        menuProcesos.add(menuAyuda);

        menuBar.add(menuProcesos);

        menuAyuda1.setMnemonic('h');
        menuAyuda1.setText("Ayuda");

        menuAyudaContenidos1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        menuAyudaContenidos1.setMnemonic('c');
        menuAyudaContenidos1.setText("Contenidos");
        menuAyuda1.add(menuAyudaContenidos1);

        menuAyudaAcercaDe1.setMnemonic('a');
        menuAyudaAcercaDe1.setText("Acerca de...");
        menuAyuda1.add(menuAyudaAcercaDe1);

        menuBar.add(menuAyuda1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuArchivoExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArchivoExportarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuArchivoExportarActionPerformed

    private void menuArchivoSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArchivoSalirActionPerformed
        DialogoSalir ds = new DialogoSalir();
        
        this.desktopPane.add("DialogoSalir", ds);
        Dimension d1 = this.desktopPane.getSize();
        Dimension d2 = ds.getSize();
        
        
        System.out.println("Desktop --> H: " + d1.getHeight() + " - W: " + d1.getWidth());
        System.out.println("JInternalFrame --> H: " + d2.getHeight() + " - W: " + d2.getWidth());
        
        Long xMiddle = Math.round((d1.getWidth() - d2.getWidth()) / 2);
        Long yMiddle = Math.round((d1.getHeight() - d2.getHeight()) / 2);
        
        System.out.println("JInternalFrame Old --> x: " + ds.getAlignmentX() + " - Y: " + ds.getAlignmentY());
        System.out.println("JInternalFrame New --> X: " + xMiddle + " - Y: " + yMiddle);
        
        ds.setBounds(Integer.parseInt(xMiddle.toString()), Integer.parseInt(yMiddle.toString()), ds.getWidth(), ds.getHeight());
        ds.setVisible(true);
    }//GEN-LAST:event_menuArchivoSalirActionPerformed

    private void menuMantenedoresDocentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMantenedoresDocentesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuMantenedoresDocentesActionPerformed

    private void menuInformeNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInformeNotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuInformeNotasActionPerformed

    private void menuInformeNotas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInformeNotas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuInformeNotas1ActionPerformed

    private void menuProcesosNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProcesosNotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuProcesosNotasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MdiApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MdiApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MdiApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MdiApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MdiApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuItem menuArchivoExportar;
    private javax.swing.JMenuItem menuArchivoSalir;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuAyuda1;
    private javax.swing.JMenuItem menuAyudaAcercaDe;
    private javax.swing.JMenuItem menuAyudaAcercaDe1;
    private javax.swing.JMenuItem menuAyudaContenidos;
    private javax.swing.JMenuItem menuAyudaContenidos1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuInformeAsistencia;
    private javax.swing.JMenuItem menuInformeAsistencia1;
    private javax.swing.JMenuItem menuInformeMatricula;
    private javax.swing.JMenuItem menuInformeMatricula1;
    private javax.swing.JMenuItem menuInformeMensualidad;
    private javax.swing.JMenuItem menuInformeMensualidad1;
    private javax.swing.JMenuItem menuInformeNotas;
    private javax.swing.JMenuItem menuInformeNotas1;
    private javax.swing.JMenu menuInformes;
    private javax.swing.JMenu menuInformes1;
    private javax.swing.JMenu menuMantenedores;
    private javax.swing.JMenuItem menuMantenedoresAdministrativos;
    private javax.swing.JMenuItem menuMantenedoresAlumnos;
    private javax.swing.JMenuItem menuMantenedoresAuxiliares;
    private javax.swing.JMenuItem menuMantenedoresDocentes;
    private javax.swing.JMenu menuProcesos;
    private javax.swing.JMenuItem menuProcesosAsistencia;
    private javax.swing.JMenuItem menuProcesosMatricula;
    private javax.swing.JMenuItem menuProcesosMensualidad;
    private javax.swing.JMenuItem menuProcesosNotas;
    // End of variables declaration//GEN-END:variables

}
